### PR TITLE
Fixes #19: support override default Flume archive URL attribute in resource

### LINKED ISSUE #19: Support override default flume archive URL attribute in the resource
To give the consumer more flexibility over how a Flume agent can be installed, it would be desirable to support an option to allow the user to override the default flume archive URL attribute in the resource such that if not specified, it would fallback to the default attribute.

### PR DESCRIPTION
**Pull request by jeffzjd**
Tagging @jrh3k5 and @jakelandis as reviewers.

### CODE REVIEW

**Comment by jrh3k5** [comment]
Sorry I took so long to merge this - getting a new laptop up and running on top of starting a new job. :) I'll get this pushed out.

**Comment by jrh3k5** [comment]
1.3.0 should now be available in Supermarket.

**Comment by jrh3k5** [comment]
Moving to 1.3.1 since I'm too damned tired to do a pull before uploading the cookbook. :/

**Comment by jeffzjd** [comment]
Thanks!

**Pull request merged**
